import { Inter } from "next/font/google";
import Head from "next/head";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movies and TV Series",
  description: "Generated by create next app",
  icons: {
    icon: "./movie.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/svg+xml" href={metadata.icons.icon} />
      </Head>
      <body className={inter.className}>
        {children}
        <Toaster position="bottom-center" reverseOrder={false} />
      </body>
    </html>
  );
}
