import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movies App",
  description: "Generated by create next app",
  icons: {
    icon: "./movie.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/svg+xml" href={metadata.icons.icon} />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
